calyx/src/calyx/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from courses import urls as course_urls
from users.urls import accounts as accounts_urls
from users.urls import jwt as jwt_urls

schema_view = get_schema_view(
    openapi.Info(
        title="Saffron API",
        default_version='v1',
        description="Saffron API documents. This API is under development.",
        license=openapi.License(name="MIT License"),
    ),
    public=True,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(jwt_urls)),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0)),
    path('', include(accounts_urls)),
    path('', include(course_urls)),
]

calyx/src/users/urls.py
from django.urls import path
from djoser import views as djoser_views
from .views import Login, Logout, MeViewSet, UserDeleteView

app_name = 'accounts'

urlpatterns = [
    path(
        'login/',
        Login.as_view(),
        name='login'
    ),
    path(
        'logout/',
        Logout.as_view(),
        name='logout'
    ),
    path(
        'password/',
        djoser_views.SetPasswordView.as_view(),
        name='set_password'
    ),
    path(
        'password/reset/',
        djoser_views.PasswordResetView.as_view(),
        name='password_reset'
    ),
    path(
        'password/reset/confirm/',
        djoser_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'
    ),
    path(
        'users/create/',
        djoser_views.UserCreateView.as_view(),
        name='user-create'
    ),
    path(
        'users/activate/',
        djoser_views.ActivationView.as_view(),
        name='user-activate'
    ),
    path(
        'me/',
        MeViewSet.as_view(),
        name='me'
    ),
    path(
        'me/delete/',
        UserDeleteView.as_view(),
        name='me-delete'
    ),
]

calyx/src/templates/base.html
<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <title>Saffron</title>
</head>
<body>
    <!-- ナビバー -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand">Calyx API</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li>
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">ログアウト</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- メインコンテント -->
    <div class="container mt-3">
        {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossorigin="anonymous"></script>
</body>